name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps: 
      - name: auto approval
        uses: pullreminders/label-when-approved-action@master
        env: 
          APPROVALS: "1"
          GITHUB_TOKEN: "77c011e56acbf559e37dd9adc344f3f1585d1cff"
          ADD_LABEL: "approved"
        
